[[redirects]]
  from = "/https://lucid-lichterman-b7efc1.netlify.app"
  to = "http://book.interpark.com"
  status = 200
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "https://lucid-lichterman-b7efc1.netlify.app/newBook"
  to = "http://book.interpark.com"
  status = 200
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "https://lucid-lichterman-b7efc1.netlify.app/recommend"
  to = "http://book.interpark.com"
  status = 200
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "https://lucid-lichterman-b7efc1.netlify.app/search"
  to = "http://book.interpark.com"
  status = 200
  force = false
  query = {path = ":path"}
